FROM node:14

COPY . /app
WORKDIR /app
RUN npm install

ARG PORT
ENV PORT=$PORT

ARG MONGO_URI
ENV MONGO_URI=$MONGO_URI

ARG SESSION_SECRET
ENV SESSION_SECRET=$SESSION_SECRET

ARG GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID

ARG GITHUB_CLIENT_SECRET
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET

EXPOSE $PORT
CMD ["npm", "start"]