version: '3'

services:
  boilerplate-advancednode-api:
    build:
      context: ../..
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
        - MONGO_URI=${MONGO_URI}
        - SESSION_SECRET=${SESSION_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    ports:
      - 3001:3001
    restart: unless-stopped