version: '3'

services:
  api:
    build:
      context: ../..
      dockerfile: ./Dockerfile
      args:
        - PORT=3001
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    restart: unless-stopped