version: '3'

services:
  boilerplate-advancednode-api:
    build:
      context: ../..
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
        - MONGO_URI=${MONGO_URI}
        - SESSION_SECRET=${SESSION_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGO_URI='mongodb+srv://arleonzemtsop:TkTrNXFDKbGaIaIT@cluster0.m9gz16i.mongodb.net/?retryWrites=true&w=majority'
      - SESSION_SECRET='session_secret_encode_key'
      - GITHUB_CLIENT_ID='eb6a320116b86564ae21'
      - GITHUB_CLIENT_SECRET='e9784775490eec80b1ed5949e540cecec7b598c8'
    restart: unless-stopped